dist: bionic
sudo: required
language: java
cache:
  directories:
  - "$HOME/.m2"
before_install:
- openssl aes-256-cbc -K $encrypted_22ed6537ee2d_key -iv $encrypted_22ed6537ee2d_iv
  -in src/main/resources/google-credentials.json.enc -out src/main/resources/google-credentials.json
  -d
jobs:
  include:
  - stage: compile
    script: "./mvnw clean package"
  - stage: compile
    script:
    - "./mvnw clean package"
    - sudo apt-get -y install python3-pip
    - python3 -V
    - pip3 -V
    - pip3 install requests
    - nohup java -jar nordic/target/nordic-0.0.1-SNAPSHOT.jar &
    - scripts/python3 health.py http://localhost:8080/actuator/health
    - sh ci-test.sh
