dist: bionic
sudo: required

language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: compile
      script: ./mvnw clean package
    - stage: compile
      script:
        - ./mvnw clean package
        - sudo apt-get -y install python3-pip
        - python3 -V
        - pip3 -V
        - pip3 install requests
        - nohup java -jar nordic/target/nordic-0.0.1-SNAPSHOT.jar &
        - scripts/python3 health.py http://localhost:8080/health
        - sh ci-test.sh
#    - stage: deploy to production
#      script: ./mvnw clean package
#      deploy: &heroku
#        provider: heroku
#        app: lift-service
#        api_key: $HEROKU_AUTH_TOKEN